name: validatable
version: 0.1.0
description: >
  Validates attributes on an object. Is supposed to be used
  together with attributable library.

author: Roman Snitko <roman.snitko@gmail.com>
homepage: https://github.com/snitko/dart-validatable
  
dependencies:
  attributable: '>=0.1.0 <0.2.0'

dev_dependencies:
  test: '>=0.12.0'
