name: validatable
version: 0.1.0
description: >
  Validates attributes on an object. Is supposed to be used
  together with attributable library.

author: Roman Snitko <roman.snitko@gmail.com>

dependencies:
  attributable:
    path: '../attributable/'

dev_dependencies:
  test: '>=0.12.0'
